export const amenitiesOptions = [
  { value: "car-parking", label: "Car Parking" },
  { value: "covered-parking", label: "Covered Parking" },
  { value: "valet-parking", label: "Valet Parking" },
  { value: "visitor-parking", label: "Visitor Parking" },
  { value: "24x7-security", label: "24/7 Security" },
  { value: "cctv", label: "CCTV Surveillance" },
  { value: "security-guards", label: "Security Guards" },
  { value: "gated-community", label: "Gated Community" },
  { value: "intercom", label: "Video Intercom" },
  { value: "swimming-pool", label: "Swimming Pool" },
  { value: "gym", label: "Gym/Fitness Center" },
  { value: "garden", label: "Garden/Lawn" },
  { value: "children-play-area", label: "Children's Play Area" },
  { value: "clubhouse", label: "Clubhouse" },
  { value: "jogging-track", label: "Jogging Track" },
  { value: "sports-court", label: "Sports Court" },
  { value: "power-backup", label: "Power Backup" },
  { value: "water-supply", label: "24/7 Water Supply" },
  { value: "waste-disposal", label: "Waste Disposal" },
  { value: "rainwater-harvesting", label: "Rainwater Harvesting" },
  { value: "solar-panels", label: "Solar Panels" },
  { value: "air-conditioning", label: "Air Conditioning" },
  { value: "modular-kitchen", label: "Modular Kitchen" },
  { value: "wardrobes", label: "Built-in Wardrobes" },
  { value: "wooden-flooring", label: "Wooden Flooring" },
  { value: "balcony", label: "Balcony/Terrace" },
  { value: "lift", label: "Lift/Elevator" },
  { value: "pet-friendly", label: "Pet Friendly" },
  { value: "senior-friendly", label: "Senior Citizen Friendly" },
  { value: "community-hall", label: "Community Hall" },
  { value: "near-school", label: "Near School" },
  { value: "near-hospital", label: "Near Hospital" },
  { value: "near-shopping", label: "Near Shopping Mall" },
  { value: "near-transport", label: "Near Public Transport" },
  { value: "main-road-facing", label: "Main Road Facing" },
  { value: "fire-safety", label: "Fire Safety Systems" },
  { value: "internet", label: "High-speed Internet" },
  { value: "housekeeping", label: "Housekeeping" },
  { value: "conference-room", label: "Conference Room" },
  { value: "business-center", label: "Business Center" },
];

export const amenitiesTypeOption = [
  { value: "apartment", label: "Apartment" },
  { value: "house", label: "House" },
  { value: "shop", label: "shop" },
  { value: "mall", label: "Mall" },
];
